# Generated by Django 4.2.7 on 2025-10-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter_identifier', 'option'), name='unique_vote_per_poll'),
        ),
    ]
