# Generated by Django 4.2.7 on 2025-12-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_vote_unique_vote_per_poll'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_per_poll',
        ),
    ]
